# Generated by Django 4.2.30 on 2026-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('BOTH', 'Both')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
