# Generated by Django 4.2.30 on 2026-09-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('odoo_record_id', models.IntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attendance_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_sync_record', to='attendance.attendanceevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OdooEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('odoo_record_id', models.IntegerField(db_index=True, unique=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_mapping_ext', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
