# Generated by Django 4.2.30 on 2026-09-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_status', models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLED', 'Enrolled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_data', models.TextField(help_text='Encrypted or serialized vector data. Do not expose via API.')),
                ('model_version', models.CharField(max_length=50)),
                ('quality_score', models.FloatField(default=0.0)),
                ('face_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='face_recognition.faceprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
