# Generated by Django 4.2.30 on 2026-09-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('liveness_score', models.FloatField(default=0.0)),
                ('recognition_status', models.CharField(max_length=50)),
                ('source', models.CharField(default='KIOSK', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='devices.attendancedevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_work_duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=50)),
                ('check_in_event', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='session_as_checkin', to='attendance.attendanceevent')),
                ('check_out_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='session_as_checkout', to='attendance.attendanceevent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['employee', 'timestamp'], name='attendance__employe_7086f1_idx'),
        ),
    ]
